apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80 # internal port to expose service
      targetPort: 5000 # forwards to container port
  type: ClusterIP
